In [1]:
import numpy as np
import torch

In [2]:
# Convert numpy to tensor OR vise-versa
np_data = np.arange(6).reshape((2, 3))
torch_data = torch.from_numpy(np_data)
tensor2array = torch_data.numpy

print(
    '\nnumpy array: \n', np_data,
    '\n\ntorch tensor: \n', torch_data,
    '\n\ntensor to array: \n', tensor2array,
)


numpy array: 
 [[0 1 2]
 [3 4 5]] 

torch tensor: 
 tensor([[0, 1, 2],
        [3, 4, 5]]) 

tensor to array: 
 <built-in method numpy of Tensor object at 0x7f29639e0bd0>


In [3]:
# Maths Function

# abs
data = [-1, -2, 1, 2]
tensor = torch.FloatTensor(data)
print(
    '\nabs',
    '\nnumpy: ', np.abs(data),
    '\ntorch: ', torch.abs(tensor)
)

# sin
print(
    '\nsin',
    '\nnumpy: ', np.sin(data),      
    '\ntorch: ', torch.sin(tensor)  
)

# mean
print(
    '\nmean',
    '\nnumpy: ', np.mean(data),     
    '\ntorch: ', torch.mean(tensor) 
)


abs 
numpy:  [1 2 1 2] 
torch:  tensor([1., 2., 1., 2.])

sin 
numpy:  [-0.84147098 -0.90929743  0.84147098  0.90929743] 
torch:  tensor([-0.8415, -0.9093,  0.8415,  0.9093])

mean 
numpy:  0.0 
torch:  tensor(0.)


In [4]:
# Matrix Multiplication
data = [[1, 2], [3, 4]]
tensor = torch.FloatTensor(data)
print(
    '\nmatrix multiplication (matmul)',
    '\n\nnumpy:\n', np.matmul(data, data),
    '\n\ntorch: \n', torch.mm(tensor, tensor)
)


matrix multiplication (matmul) 

numpy:
 [[ 7 10]
 [15 22]] 

torch: 
 tensor([[ 7., 10.],
        [15., 22.]])
