In [1]:
import torch
from torch.autograd import Variable

In [2]:
# Variable in torch is to build a computational graph
# but this graph is dynamic compared with a static graph
# in Tf. So torch doesnot have placeholder, torch can just
# pass variable to the computational graph.

tensor = torch.FloatTensor([[1,2], [3, 4]])
# Build a variable, usually to compute gradients
variable = Variable(tensor, requires_grad=True)

print(tensor)
print(variable)

tensor([[1., 2.],
        [3., 4.]])
tensor([[1., 2.],
        [3., 4.]], requires_grad=True)


In [3]:
# Till now the tensor and variable seem the same
# However, the variable is a part of the graph,
# it's a part of the auto-gradient

t_out = torch.mean(tensor*tensor)
v_out = torch.mean(variable*variable)
print(t_out)
print(v_out)

tensor(7.5000)
tensor(7.5000, grad_fn=<MeanBackward1>)


In [4]:
v_out.backward() # backpropagation from v_out
print(variable.grad)

tensor([[0.5000, 1.0000],
        [1.5000, 2.0000]])


In [5]:
print(variable)

tensor([[1., 2.],
        [3., 4.]], requires_grad=True)


In [6]:
print(variable.data)

tensor([[1., 2.],
        [3., 4.]])


In [7]:
print(variable.data.numpy())

[[1. 2.]
 [3. 4.]]
