# Numpy
Numpy is the fundamental package for scientific computing with python.

In [6]:
import numpy as np
np.__version__

'1.14.0'

## Creating Arrays from Python Lists
First, we can use `np.array` to create arrays from Python lists:

In [10]:
# interger array
np.array([1, 4, 2, 5, 3])

array([1, 4, 2, 5, 3])

In [11]:
# Unlike Python lists, NumPy is constrained
# to arrays that all contain the same type
np.array([3.14, 1, 2, 3])

array([3.14, 1.  , 2.  , 3.  ])

In [12]:
# We can set explicitly the data type
np.array([1, 2, 3, 4], dtype='float32')

array([1., 2., 3., 4.], dtype=float32)

In [13]:
# Unlike Python lists, NumPy arrays can explicitly be 
# multi-dimensional
np.array([range(i, i + 3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

## Creating Arrays from Scratch
Especially for larger arrays, it is more efficient to create arrays from scratch using routines built into NumPy.

In [15]:
# Create a length-10 integer array filled with zeros
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [16]:
# Create a 3X5 floating array filled with ones
np.ones((3,5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [17]:
# Create a 3X5 array filled with 3.14
np.full((3,5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [19]:
# Create an array filled with a linear squence
# Starting at 0, ending at 20, stepping by 2
# (this is similar to built-in range() function)
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [20]:
# Create an array of five values evenly spaced between 0 and 1
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [21]:
# Create an 3X3 array of uniformly distributed
# random values between 0 and 1
np.random.random((3, 3))

array([[0.06471817, 0.05169616, 0.89854695],
       [0.72415962, 0.01378607, 0.33608192],
       [0.165663  , 0.05625723, 0.93271298]])

In [28]:
# Create a 3X3 array of noramlly distributed random values
# with mean 0 and standard deviation 1
np.random.normal(0, 1, (3, 3))

array([[ 0.37755248,  0.42505685, -1.59250677],
       [ 0.41236117,  0.31632365, -0.64586097],
       [-0.02600983, -1.28485065, -0.45397783]])

In [30]:
# Create a 3x3 array of random integers in interval [0, 10)
np.random.randint(0, 10, (3, 3))

array([[1, 1, 4],
       [0, 2, 2],
       [5, 6, 1]])

In [31]:
# Create a 3x3 identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [32]:
# Create an uninitialized array of three integers
# The values will be whatever happens to already exist
# at that memory location
np.empty(3)

array([1., 1., 1.])

## Numpy Array Attributes

In [37]:
np.random.seed(0)  # seed for reproducibility

x1 = np.random.randint(10, size=6) # 1-D array
x2 = np.random.randint(10, size=(3, 4)) # 2-D array
x3 = np.random.randint(10, size=(3, 4, 5)) # 3-D array

In [35]:
print("x3 dim: ", x3.ndim) # number of dimensions
print("x3 shape: ", x3.shape) # size of each dimensions
print("x3 size: ", x3.size) # total size of the array

x3 dim:  3
x3 shape:  (3, 4, 5)
x3 size:  60


In [38]:
# Print data type of the array
print("dtype: ", x3.dtype)

dtype:  int32


In [39]:
# Print size of each element and total size
print("itemsize: ", x3.itemsize, "bytes")
print("nbytes: ", x3.nbytes, "bytes")

itemsize:  4 bytes
nbytes:  240 bytes


## Array Indexing: Accessing Single Elements

In [40]:
x1

array([5, 0, 3, 3, 7, 9])

In [41]:
x1[0]

5

In [42]:
x1[4]

7

In [43]:
# Print from the end of the array
x1[-1]

9

In [44]:
x1[-2]

7

In [45]:
# In 2-D array
x2[0, 0]

3

In [46]:
x2[2, -1]

7

In [50]:
# Modify the first element
x2[0, 0] = 12
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [52]:
# Unlike Python lists, NumPy arrays have a fixed type
# If you attempt to insert a floating-point value to an integer array,
# the value will be silently truncated
x1[0] = 3.141
x1

array([3, 0, 3, 3, 7, 9])

# Array Slicing: Accessing Subarrays
NumPy slicing syntax: `x[start:stop:step]`. If any of these are unspecified, they default to the values `start=0`, `stop= size of dimension`, `step=1`.

### One-dimensional subarrays

In [54]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [55]:
x[:5] # first five elements

array([0, 1, 2, 3, 4])

In [56]:
x[5:] # elements after index 5

array([5, 6, 7, 8, 9])

In [57]:
x[4:7] # middle sub-array

array([4, 5, 6])

In [58]:
x[::2] # every other element

array([0, 2, 4, 6, 8])

In [59]:
x[1::2] # every other element starting at 1

array([1, 3, 5, 7, 9])

A potentially confusing case is when the `step` value is negative. In this case, the defaults for `start` and `stop` are swapped. This becomes a convenient way to reverse an array:

In [60]:
x[::-1] # all elements, reversed

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [63]:
x[5::-2] # reversed every other from index 5

array([5, 3, 1])

### Multi-dimensional subarrays
Multi-dimensional slices work in the same way, with multiple slices separated by commas. <br>
Syntax of 2-D arrays:<br> `x[start(r):stop(r):step(r), start(c):stop(c):step(c)]`
<br> For example:

In [68]:
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [69]:
x2[:2, :3] # two rows, three columns

array([[12,  5,  2],
       [ 7,  6,  8]])

In [71]:
x2[:3, ::2] # all rows, every other colum

array([[12,  2],
       [ 7,  8],
       [ 1,  7]])

In [74]:
x2[::-1, ::-1] # reversed 

array([[ 7,  7,  6,  1],
       [ 8,  8,  6,  7],
       [ 4,  2,  5, 12]])

#### Accessing array rows and columns
One commonly needed routine is accessing of single rows or columns of an array. This can be done by combining indexing and slicing, using an empty slice marked by a single colon (`:`):

In [75]:
print(x2[:, 0]) # first column of x2

[12  7  1]


In [80]:
print(x2[0, :]) # first row of x2

[12  5  2  4]


In [81]:
print(x2[0]) # equivalent to x2[0, :]

[12  5  2  4]


### Subarrays as no-copy views
One important–and extremely useful–thing to know about array slices is that they return views rather than copies of the array data. This is one area in which NumPy array slicing differs from Python list slicing: in lists, slices will be copies. Consider our two-dimensional array from before:

In [87]:
print(x2)

[[12  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


In [88]:
x2_sub = x2[:2, :2]
print(x2_sub)

[[12  5]
 [ 7  6]]


In [89]:
# Now if we modify this subarray,
# we'll see that the original array is change!
x2_sub[0, 0] = 99
print(x2_sub)

[[99  5]
 [ 7  6]]


In [90]:
print(x2)

[[99  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


### Creating copies of arrays
Despite the nice features of array views, it is sometimes useful to instead explicitly copy the data within an array or a subarray. This can be most easily done with the `copy()` method:

In [91]:
x2_sub_copy = x2[:2, :2].copy()
print(x2_sub_copy)

[[99  5]
 [ 7  6]]


In [92]:
x2_sub_copy[0, 0] = 42
print(x2_sub_copy)

[[42  5]
 [ 7  6]]


In [93]:
print(x2)

[[99  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


## Reshaping of Arrays
For example: Put the numbers 1 through 9 in a grid of 3X3:

In [96]:
grid = np.arange(1, 10).reshape((3,3))
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


Another common reshaping pattern is the conversion of a one-dimensional array into a two-dimensional row or column matrix. This can be done with the reshape method, or more easily done by making use of the newaxis keyword within a slice operation:

In [97]:
x = np.array([1, 2, 3])

# row vector via reshape
x.reshape((1, 3))

array([[1, 2, 3]])

In [100]:
# row vector via newaxis
x[np.newaxis, :]

array([[1, 2, 3]])

In [101]:
# column vector via reshape
x.reshape((3, 1))

array([[1],
       [2],
       [3]])

In [102]:
# column vector via newaxis
x[:, np.newaxis]

array([[1],
       [2],
       [3]])

## Array Concatenation and Splitting
All of the preceding routines worked on single arrays. It's also possible to combine multiple arrays into one, and to conversely split a single array into multiple arrays. We'll take a look at those operations here.

### Concatenation of arrays
Concatenation, or joining of two arrays in NumPy, is primarily accomplished using the routines `np.concatenate`, `np.vstack`, and `np.hstack`.<br> `np.concatenate` takes a tuple or list of arrays as its first argument, as we can see here:

In [103]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

In [106]:
z = [99.1, 99.1, 99.1]
print(np.concatenate([x, y, z]))

[ 1.   2.   3.   3.   2.   1.  99.1 99.1 99.1]


In [113]:
grid = np.array([[1, 2, 3],
                 [4, 5, 6]])

In [114]:
# concatenate along the first axis
np.concatenate([grid, grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [116]:
# concatenate along the second axis (zero-indexed)
np.concatenate([grid, grid], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

`np.vstack` (vertical stack) and `np.hstack` (horizontal stack)

In [117]:
x = np.array([1, 2, 3])
grid = np.array([[9, 8, 7],
                 [6, 5, 4]])

# vertically stack the arrays
np.vstack([x, grid])

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [118]:
# horizontally stack the arrays
y = np.array([[99],
              [99]])
np.hstack([grid, y])

array([[ 9,  8,  7, 99],
       [ 6,  5,  4, 99]])

Similarly, `np.dstack` will stack arrays along the third axis.

### Splitting of arrays
The opposite of concatenation is splitting, which is implemented by the functions `np.split`, `np.hsplit`, and `np.vsplit`.

In [119]:
x = [1, 2, 3, 99, 99, 3, 2, 1]
x1, x2, x3 = np.split(x, [3, 5])
print(x1, x2, x3)

[1 2 3] [99 99] [3 2 1]


Notice that N split-points, leads to N + 1 subarrays. The related functions np.hsplit and np.vsplit are similar.

Similarly, `np.dsplit` will split arrays along the third axis.